name: RadicalWisdom
favicon: null
layout_spectrum: 0.18150417576543987
typography_spectrum: 0.6776760525535792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.17554301372729242
  lightness: 0.7785517468582839
  saturation: 0.47837021481245756
  rhythmicContrast: 0.3448522360995412
purpose: []
